server:
  port: 8092
  servlet:
    context-path: /wxp

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spbt
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    call-setters-on-nulls: true


logging.level.org.springframework.security: DEBUG
logging.level.per.wxp.rtml.sys.mapper: DEBUG